#!/bin/bash

# Author: guan-gm lin <guan-gm.lin@mediatek.com>

salt_file=$1
header=$2

openssl rand 32 > $salt_file

echo "/*" > $header
echo " * This file is auto-generated by gen_salt" >> $header
echo " * please do not modify this file manually" >> $header
echo " */" >> $header


echo "#ifndef SALT_H" >> $header
echo "#define SALT_H" >> $header
echo "#define MTK_FIP_ENC_SALT { \\" >> $header
echo -ne '\t' >> $header
cat salt | hexdump -ve '/1 "0x%02x, "' >> $header
echo "\\" >> $header
echo "}" >> $header
echo "#endif" >> $header
