# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - '*-bpi'
    - '*-ci'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install depencies
        run: |
          sudo apt update
          sudo apt install ccache libssl-dev u-boot-tools gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu make python3-pyelftools

      - name: Setup env
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "UBOOTVER=$(make ubootversion)" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo $BRANCH $UBOOTVER $DT

      - name: Setup cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache/
          key: ${{ runner.os }}-ccache-uboot-${{ env.UBOOTVER }}
          restore-keys: ${{ runner.os }}-ccache-uboot-${{ env.UBOOTVER }}

      - name: Fetch mtk-atf branch
        run: |
          git fetch origin mtk-atf-2025

      - name: Build for BananaPi-R2
        run: |
          export PATH=/usr/lib/ccache:$PATH
          echo -e "board=bpi-r2" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh createimg
          bash build.sh rename

      - name: Build for BananaPi-R64
        run: |
          echo -e "board=bpi-r64" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r64\ndevice=sdmmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive

          make realclean
          echo -e "board=bpi-r64\ndevice=emmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive

          rm build.conf

          git checkout ${{ env.BRANCH }}

      - name: Build for BananaPi-R2Pro
        run: |
          echo -e "board=bpi-r2pro" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh createimg
          bash build.sh rename
          git checkout build.conf

      - name: Build for BananaPi-R3 (SD)
        run: |
          echo -e "board=bpi-r3" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3\ndevice=sdmmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive
          rm build.conf

      - name: Build for BananaPi-R3 (EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r3\ndevice=emmc" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3\ndevice=emmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive
          rm build.conf

      - name: Build for BananaPi-R3 (NAND)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r3\ndevice=spi-nand" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3\ndevice=spim-nand" > build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=UBI=1" >> build.conf
          bash build.sh build
          bash build.sh rename
          rm build.conf

      - name: Build for BananaPi-R3 (NOR)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r3\ndevice=spi-nor" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3\ndevice=nor" > build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=UBI=1" >> build.conf
          bash build.sh build
          bash build.sh rename
          rm build.conf

      - name: Build for BananaPi-R3 (RAM/EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r3\ndevice=emmc" > build.conf
          sed -i 's/^bootcmd/#bootcmd/' uEnv_r3.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r3.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3\ndevice=ram" > build.conf
          bash build.sh build
          bash build.sh rename
          rm build.conf

      - name: Build for BananaPi-R3Mini (EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r3mini\ndevice=emmc" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3mini\ndevice=emmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive
          rm build.conf

      - name: Build for BananaPi-R3Mini (NAND)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r3mini\ndevice=spi-nand" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3mini\ndevice=spim-nand" > build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=UBI=1" >> build.conf
          bash build.sh build
          bash build.sh rename
          rm build.conf

      - name: Build for BananaPi-R3Mini (RAM/EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r3mini\ndevice=emmc" > build.conf
          sed -i 's/^bootcmd/#bootcmd/' uEnv_r3.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r3.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r3mini\ndevice=ram" > build.conf
          bash build.sh build
          bash build.sh rename
          rm build.conf

      - name: Build for BananaPi-R4 (SD)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4\ndevice=sdmmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive
          make realclean
          echo -e "extraflags=DDR4_4BG_MODE=1" >> build.conf
          bash build.sh build
          bash build.sh rename

          rm build.conf

      - name: Build for BananaPi-R4 (EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4\ndevice=emmc" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4\ndevice=emmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive
          make realclean
          echo -e "extraflags=DDR4_4BG_MODE=1" >> build.conf
          bash build.sh build
          bash build.sh rename

          rm build.conf

      - name: Build for BananaPi-R4 (NAND)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4\ndevice=spi-nand" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4\ndevice=spim-nand" > build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=UBI=1" >> build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=DDR4_4BG_MODE=1" >> build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags='UBI=1 DDR4_4BG_MODE=1'" >> build.conf
          bash build.sh build
          bash build.sh rename

          rm build.conf

      - name: Build for BananaPi-R4 (RAM/EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4\ndevice=emmc" > build.conf
          sed -i 's/^bootcmd/#bootcmd/' uEnv_r4.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r4.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4\ndevice=ram" > build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=DDR4_4BG_MODE=1" >> build.conf
          bash build.sh build
          bash build.sh rename

          rm build.conf

      - name: Build for BananaPi-R4 Pro (SD)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4pro" > build.conf
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4\ndevice=sdmmc" > build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=DDR4_4BG_MODE=1" >> build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive

          rm build.conf

      - name: Build for BananaPi-R4 Lite (SD)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4lite" > build.conf
          echo "isr4lite=1" >> uEnv_r4.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r4.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4lite\ndevice=sdmmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash -x build.sh createimg non-interactive

          rm build.conf

      - name: Build for BananaPi-R4 Lite (EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4lite\ndevice=emmc" > build.conf
          echo "isr4lite=1" >> uEnv_r4.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r4.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4lite\ndevice=emmc" > build.conf
          bash build.sh build
          bash build.sh rename
          bash build.sh createimg non-interactive

          rm build.conf

      - name: Build for BananaPi-R4 Lite (NAND)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4lite\ndevice=spi-nand" > build.conf
          echo "isr4lite=1" >> uEnv_r4.txt
          sed -i 's/^bootmenu_default=2/bootmenu_default=4/' uEnv_r4.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r4.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4lite\ndevice=spim-nand" > build.conf
          echo -e "extraflags=UBI=1" >> build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=UBI=1" >> build.conf
          bash build.sh build
          bash build.sh rename

          rm build.conf

      - name: Build for BananaPi-R4 Lite (NOR)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4lite\ndevice=spi-nor" > build.conf
          echo "isr4lite=1" >> uEnv_r4.txt
          sed -i 's/^bootmenu_default=2/bootmenu_default=4/' uEnv_r4.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r4.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4lite\ndevice=nor" > build.conf
          bash build.sh build
          bash build.sh rename
          make realclean
          echo -e "extraflags=UBI=1" >> build.conf
          bash build.sh build
          bash build.sh rename

          rm build.conf

      - name: Build for BananaPi-R4 Lite (RAM/EMMC)
        run: |
          git checkout ${{ env.BRANCH }}
          echo -e "board=bpi-r4lite\ndevice=emmc" > build.conf
          echo "isr4lite=1" >> uEnv_r4.txt
          sed -i 's/^bootcmd/#bootcmd/' uEnv_r4.txt
          bash build.sh importconfig
          bash build.sh build
          bash build.sh rename
          git checkout build.conf uEnv_r4.txt

          git checkout mtk-atf-2025
          echo -e "board=bpi-r4lite\ndevice=ram" > build.conf
          bash build.sh build
          bash build.sh rename

          rm build.conf

      - name: Upload binaries to release
        if: endsWith(github.ref,'-bpi') && contains(env.UBOOTVER,'-rc') == false
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "CI-BUILD-${{ env.BRANCH }}-${{ env.UBOOTVER }}-${{ env.DT }}"
          prerelease: false
          title: "Build for branch ${{ env.BRANCH }} (${{ env.UBOOTVER }})"
          files: |
            u-boot-r2*.bin
            u-boot-r64*.bin
            u-boot-r3*.bin
            u-boot-r4*.bin
            *_fip.bin
            *_bl2.img
            *ram*_bl2.bin
            *.img.gz
